CREATE DATABASE sanitation;

CREATE TABLE users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE sanitation_data (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  distance_covered FLOAT NOT NULL,
  trash_disposed INT(6) NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


